global class Inverite_Bank_Account {
    global String bank{get;set;}
    global String institution{get;set;}
    global String transit{get;set;}
    global String routing_code{get;set;}
    global String account{get;set;}
    global String type{get;set;}
    global String membership_number{get;set;}
    global String account_description{get;set;}
    global Transactions[] transactions{get;set;}
  //  global PaySchedules[] Payschedules{get;set;}
}