global class InveriteWebhookRequest {
    global String complete_datetime{get;set;}
    global String request{get;set;}
    global InveriteWebhook_Account[] accounts{get;set;}
    global InveriteWebhook_Contact[] contacts{get;set;}
    global String status{get;set;}
    global String error{get;set;}
    global String name{get;set;}
    global String address{get;set;}
    global String referenceid{get;set;}
    global String type{get;set;}
}